from __future__ import annotations

from datetime import datetime

from retro.utils.logger import get_logger

logger = get_logger(__name__)

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RETRO Incident Report - {incident_id}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #0d1117; color: #c9d1d9; }}
  .container {{ max-width: 1000px; margin: 0 auto; }}
  h1 {{ color: #f78166; border-bottom: 2px solid #30363d; padding-bottom: 10px; }}
  h2 {{ color: #58a6ff; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; margin: 16px 0; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }}
  .badge-high {{ background: #da3633; color: white; }}
  .badge-medium {{ background: #d29922; color: black; }}
  .badge-low {{ background: #238636; color: white; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
  th, td {{ text-align: left; padding: 8px; border-bottom: 1px solid #30363d; }}
  th {{ color: #8b949e; }}
  .footer {{ text-align: center; color: #484f58; margin-top: 40px; font-size: 12px; }}
  pre {{ background: #0d1117; padding: 10px; border-radius: 4px; overflow-x: auto; }}
</style>
</head>
<body>
<div class="container">
  <h1>RETRO Incident Report</h1>
  <div class="card">
    <h2>Incident Summary</h2>
    <table>
      <tr><th>ID</th><td>{incident_id}</td></tr>
      <tr><th>Date</th><td>{date}</td></tr>
      <tr><th>Source IP</th><td>{source_ip}</td></tr>
      <tr><th>Event Type</th><td>{event_type}</td></tr>
      <tr><th>Sensor</th><td>{sensor}</td></tr>
      <tr><th>Threat Score</th><td><span class="badge badge-{score_level}">{threat_score:.1f}</span></td></tr>
    </table>
  </div>
  <div class="card">
    <h2>OSINT Data</h2>
    <pre>{osint_data}</pre>
  </div>
  <div class="card">
    <h2>Countermeasures Applied</h2>
    <pre>{countermeasures}</pre>
  </div>
  <div class="footer">
    <p>Generated by RETRO v0.1.0 — Active Defense Platform</p>
  </div>
</div>
</body>
</html>"""


async def generate_html_report(incident: dict) -> str:
    score = incident.get("threat_score", 0)
    if score >= 0.7:
        level = "high"
    elif score >= 0.4:
        level = "medium"
    else:
        level = "low"
    return REPORT_TEMPLATE.format(
        incident_id=incident.get("id", "N/A"),
        date=incident.get("timestamp", datetime.utcnow().isoformat()),
        source_ip=incident.get("source_ip", "N/A"),
        event_type=incident.get("event_type", "N/A"),
        sensor=incident.get("sensor", "N/A"),
        threat_score=score,
        score_level=level,
        osint_data=str(incident.get("osint", {})),
        countermeasures=str(incident.get("countermeasures", [])),
    )
